[target.x86_64-unknown-linux-musl]
rustflags = "-Ctarget-feature=-crt-static"

[target.aarch64-unknown-linux-musl]
rustflags = "-Ctarget-feature=-crt-static"

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.arm-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"

[target.arm7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

